
import java.awt.Color;
import java.awt.Image;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author mkjch
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        javax.swing.JPanel jPanel4 = new javax.swing.JPanel();
        close = new javax.swing.JButton();
        viewStudent = new javax.swing.JButton();
        sedTeacher = new javax.swing.JButton();
        addTeacher = new javax.swing.JButton();
        sedStudent = new javax.swing.JButton();
        viewTeacher = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        addStudent = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        logout = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setMinimumSize(new java.awt.Dimension(640, 460));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(36, 47, 65));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancelLight.png"))); // NOI18N
        close.setBorderPainted(false);
        close.setContentAreaFilled(false);
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        jPanel4.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 30, -1));

        viewStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/viewStudentDetails.png"))); // NOI18N
        viewStudent.setBorder(null);
        viewStudent.setBorderPainted(false);
        viewStudent.setContentAreaFilled(false);
        viewStudent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewStudent.setDefaultCapable(false);
        viewStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewStudentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewStudentMouseExited(evt);
            }
        });
        viewStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewStudentActionPerformed(evt);
            }
        });
        jPanel4.add(viewStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, -1, -1));

        sedTeacher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SearchEditDeleteTeacher.png"))); // NOI18N
        sedTeacher.setBorder(null);
        sedTeacher.setBorderPainted(false);
        sedTeacher.setContentAreaFilled(false);
        sedTeacher.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sedTeacher.setDefaultCapable(false);
        sedTeacher.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                sedTeacherMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                sedTeacherMouseMoved(evt);
            }
        });
        sedTeacher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sedTeacherMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sedTeacherMouseExited(evt);
            }
        });
        sedTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sedTeacherActionPerformed(evt);
            }
        });
        jPanel4.add(sedTeacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, -1, -1));

        addTeacher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addTeacher.png"))); // NOI18N
        addTeacher.setBorder(null);
        addTeacher.setBorderPainted(false);
        addTeacher.setContentAreaFilled(false);
        addTeacher.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addTeacher.setDefaultCapable(false);
        addTeacher.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                addTeacherMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                addTeacherMouseMoved(evt);
            }
        });
        addTeacher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addTeacherMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addTeacherMouseExited(evt);
            }
        });
        addTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTeacherActionPerformed(evt);
            }
        });
        jPanel4.add(addTeacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        sedStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/searchEditDeleteStudent.png"))); // NOI18N
        sedStudent.setBorder(null);
        sedStudent.setBorderPainted(false);
        sedStudent.setContentAreaFilled(false);
        sedStudent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sedStudent.setDefaultCapable(false);
        sedStudent.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                sedStudentMouseMoved(evt);
            }
        });
        sedStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sedStudentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sedStudentMouseExited(evt);
            }
        });
        sedStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sedStudentActionPerformed(evt);
            }
        });
        jPanel4.add(sedStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        viewTeacher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ViewTeachersDetails.png"))); // NOI18N
        viewTeacher.setBorder(null);
        viewTeacher.setBorderPainted(false);
        viewTeacher.setContentAreaFilled(false);
        viewTeacher.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewTeacher.setDefaultCapable(false);
        viewTeacher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewTeacherMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewTeacherMouseExited(evt);
            }
        });
        viewTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTeacherActionPerformed(evt);
            }
        });
        jPanel4.add(viewTeacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, -1, -1));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(97, 212, 195));
        jLabel2.setText("VIEW DETAILS");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, -1, 27));

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(97, 212, 195));
        jLabel5.setText("SEARCH/EDIT/DELETE");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, -1, 27));

        addStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addStudent.png"))); // NOI18N
        addStudent.setBorder(null);
        addStudent.setBorderPainted(false);
        addStudent.setContentAreaFilled(false);
        addStudent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addStudent.setDefaultCapable(false);
        addStudent.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                addStudentMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                addStudentMouseMoved(evt);
            }
        });
        addStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addStudentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addStudentMouseExited(evt);
            }
        });
        addStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentActionPerformed(evt);
            }
        });
        jPanel4.add(addStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(97, 212, 195));
        jLabel6.setText("ADD STUDENT");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, 27));

        jLabel7.setBackground(new java.awt.Color(204, 204, 204));
        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(97, 212, 195));
        jLabel7.setText("ADD TEACHER");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, 27));

        jPanel3.setBackground(new java.awt.Color(97, 212, 195));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logout.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        logout.setForeground(new java.awt.Color(36, 47, 65));
        logout.setText("LOGOUT");
        logout.setBorder(null);
        logout.setBorderPainted(false);
        logout.setContentAreaFilled(false);
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel3.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, -1, -1));

        jLabel8.setBackground(new java.awt.Color(204, 204, 204));
        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(97, 212, 195));
        jLabel8.setText("SEARCH/EDIT/DELETE");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, 27));

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(97, 212, 195));
        jLabel4.setText("VIEW DETAILS");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, -1, 27));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 500, 500));

        jPanel9.setBackground(new java.awt.Color(97, 212, 195));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(36, 47, 65));
        jLabel3.setText("HOME");
        jPanel9.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 27));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/studentBackground.png"))); // NOI18N
        jPanel9.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-440, -10, 590, 540));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        System.exit(0);
    }//GEN-LAST:event_closeActionPerformed

    private void viewStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewStudentActionPerformed
      setVisible(false);
        AllStudents view = new AllStudents();
        view.setVisible(true);
    }//GEN-LAST:event_viewStudentActionPerformed

    private void sedTeacherMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sedTeacherMouseMoved

    }//GEN-LAST:event_sedTeacherMouseMoved

    private void sedTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sedTeacherActionPerformed
        setVisible(false);
        UpdateTeacher view = new UpdateTeacher();
        view.setVisible(true);
    }//GEN-LAST:event_sedTeacherActionPerformed

    private void sedStudentMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sedStudentMouseMoved

    }//GEN-LAST:event_sedStudentMouseMoved

    private void sedStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sedStudentActionPerformed
        setVisible(false);
        updateStudent view = new updateStudent();
        view.setVisible(true);
    }//GEN-LAST:event_sedStudentActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        setVisible(false);
        Login log = new Login();
        log.setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void sedTeacherMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sedTeacherMouseDragged

    }//GEN-LAST:event_sedTeacherMouseDragged

    private void sedTeacherMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sedTeacherMouseEntered
        try {
            Image img = ImageIO.read(getClass().getResource("images/SearchEditDeleteTeacherHover.png"));
            sedTeacher.setIcon(new ImageIcon(img));
        } catch (IOException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_sedTeacherMouseEntered

    private void sedTeacherMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sedTeacherMouseExited
        try {
            Image img = ImageIO.read(getClass().getResource("images/SearchEditDeleteTeacher.png"));
            sedTeacher.setIcon(new ImageIcon(img));
        } catch (IOException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_sedTeacherMouseExited

    private void sedStudentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sedStudentMouseEntered
        try {
            Image img = ImageIO.read(getClass().getResource("images/searchEditDeleteStudentHover.png"));
            sedStudent.setIcon(new ImageIcon(img));
        } catch (IOException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_sedStudentMouseEntered

    private void sedStudentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sedStudentMouseExited
        try {
            Image img = ImageIO.read(getClass().getResource("images/searchEditDeleteStudent.png"));
            sedStudent.setIcon(new ImageIcon(img));
        } catch (IOException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_sedStudentMouseExited

    private void viewStudentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewStudentMouseEntered
        try {
            Image img = ImageIO.read(getClass().getResource("images/viewStudentDetailsHover.png"));
            viewStudent.setIcon(new ImageIcon(img));
        } catch (IOException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_viewStudentMouseEntered

    private void viewStudentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewStudentMouseExited
        try {
            Image img = ImageIO.read(getClass().getResource("images/viewStudentDetails.png"));
            viewStudent.setIcon(new ImageIcon(img));
        } catch (IOException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_viewStudentMouseExited

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
       
    }//GEN-LAST:event_jPanel3MouseEntered

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        logout.setOpaque(true);
        logout.setBackground(new Color(191,255,245));
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        logout.setOpaque(false);
    }//GEN-LAST:event_logoutMouseExited

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
      try {
            Image img = ImageIO.read(getClass().getResource("images/cancelLightHover.png"));
            close.setIcon(new ImageIcon(img));
        } catch (IOException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        try {
            Image img = ImageIO.read(getClass().getResource("images/cancelLight.png"));
            close.setIcon(new ImageIcon(img));
        } catch (IOException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_closeMouseExited

    private void addStudentMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addStudentMouseDragged
        
    }//GEN-LAST:event_addStudentMouseDragged

    private void addStudentMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addStudentMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_addStudentMouseMoved

    private void addStudentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addStudentMouseEntered
      try {
            Image img = ImageIO.read(getClass().getResource("images/addStudentHover.png"));
            addStudent.setIcon(new ImageIcon(img));
        } catch (IOException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addStudentMouseEntered

    private void addStudentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addStudentMouseExited
      try {
            Image img = ImageIO.read(getClass().getResource("images/addStudent.png"));
            addStudent.setIcon(new ImageIcon(img));
        } catch (IOException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addStudentMouseExited

    private void addStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentActionPerformed
        setVisible(false);
        addStudent view = new addStudent();
        view.setVisible(true);
    }//GEN-LAST:event_addStudentActionPerformed

    private void addTeacherMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addTeacherMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_addTeacherMouseDragged

    private void addTeacherMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addTeacherMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_addTeacherMouseMoved

    private void addTeacherMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addTeacherMouseEntered
         try {
            Image img = ImageIO.read(getClass().getResource("images/addTeacherHover.png"));
            addTeacher.setIcon(new ImageIcon(img));
        } catch (IOException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addTeacherMouseEntered

    private void addTeacherMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addTeacherMouseExited
         try {
            Image img = ImageIO.read(getClass().getResource("images/addTeacher.png"));
            addTeacher.setIcon(new ImageIcon(img));
        } catch (IOException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addTeacherMouseExited

    private void addTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTeacherActionPerformed
        setVisible(false);
        Teacher view = new Teacher();
        view.setVisible(true);
    }//GEN-LAST:event_addTeacherActionPerformed

    private void viewTeacherMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewTeacherMouseEntered
        try {
            Image img = ImageIO.read(getClass().getResource("images/ViewTeachersDetailsHover.png"));
            viewTeacher.setIcon(new ImageIcon(img));
        } catch (IOException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_viewTeacherMouseEntered

    private void viewTeacherMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewTeacherMouseExited
        try {
            Image img = ImageIO.read(getClass().getResource("images/ViewTeachersDetails.png"));
            viewTeacher.setIcon(new ImageIcon(img));
        } catch (IOException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_viewTeacherMouseExited

    private void viewTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTeacherActionPerformed
        setVisible(false);
        AllTeachers view = new AllTeachers();
        view.setVisible(true);
    }//GEN-LAST:event_viewTeacherActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addStudent;
    private javax.swing.JButton addTeacher;
    private javax.swing.JButton close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton logout;
    private javax.swing.JButton sedStudent;
    private javax.swing.JButton sedTeacher;
    private javax.swing.JButton viewStudent;
    private javax.swing.JButton viewTeacher;
    // End of variables declaration//GEN-END:variables
}
